Dolvano/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include('main.urls')),
    path("", include('cart.urls')),

    path('', include('account.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='index'),
    path('acc/signup/', views.signup, name='signup'),
    path('acc/activate/', views.activate, name='activate'),
]

cart/urls.py
from django.template.defaulttags import url
from django.urls import path
from .views import cart, update_cart

urlpatterns = [
    path('cart/', cart, name='cart'),
    path('update_cart/', update_cart, name='update_cart'),
]

main/urls.py
from django.template.defaulttags import url
from django.urls import path, include
from .views import *

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),

    path('ShowClocks/', wallclocks_list, name='wallclocks_list'),

    path('Decorations/', decoration_list, name='decorations_link'),

    path('Fireplace/', fireplace_list, name='fireplace_list'),

    path('Dolvano_home/', dolvano_home_list, name='dolvano_home_list'),

    path('Special_Orders/', special_orders_list, name='special_orders_list'),

    path('Info/', information, name='information'),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    path('live-search/', live_search, name='live_search'),

    path('Product/<int:product_pk>', product_page, name='product_page'),


]

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from main.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_total_cart_price(self):
        product_items = self.cartitemlist_set.all()
        total_price = sum([product.get_product_total_price for product in product_items])
        return total_price

    @property
    def get_cart_total_quantity(self):
        items = self.cartitemlist_set.all()
        total_items = sum([product.quantity for product in items])
        return total_items


class CartItemList(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_product_total_price(self):
        total_items_price = self.product.price * self.quantity
        return total_items_price

    def __str__(self):
        return self.product.name

main/models.py
from django.db import models


class Product(models.Model):
    rubric = models.ForeignKey("Rubric", on_delete=models.CASCADE, blank=True, null=True, verbose_name='Ռուբրիկա')
    popular = models.BooleanField(null=True, blank=True, default=False)
    name = models.CharField(max_length=200, verbose_name='Անուն')
    product_code = models.CharField(max_length=200, verbose_name='Կոդ')
    color = models.ForeignKey('Color', on_delete=models.CASCADE, verbose_name="Գույն", null=True, blank=True)
    mini_description = models.TextField(verbose_name='Փոքր նկարագիր')
    card_photo = models.ImageField(upload_to='clock_photos/', verbose_name='Քարտի նկար 220x220')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Գինը')
    background_photo = models.ImageField(upload_to='clock_photos/', verbose_name='Բաների նկար')
    info_image_1 = models.ImageField(upload_to='clock_photos/', verbose_name='Ինֆո 1 նկար')
    info_header_1 = models.TextField(verbose_name='Ինֆո 1 վերնագգիր ', null=True, blank=True)
    info_description_1 = models.TextField(verbose_name='Ինֆո 1 ')
    info_image_2 = models.ImageField(upload_to='clock_photos/', verbose_name='Ինֆո 2 նկար')
    info_header_2 = models.TextField(verbose_name='Ինֆո 2 վերնագգիր ', null=True, blank=True)
    info_description_2 = models.TextField(verbose_name='Ինֆո 2 ',)
    info_image_3 = models.ImageField(upload_to='clock_photos/', verbose_name='Ինֆո 3 նկար')
    info_header_3 = models.TextField(verbose_name='Ինֆո 3 վերնագգիր', null=True, blank=True)
    info_description_3 = models.TextField(verbose_name='Ինֆո 3 ')
    slider_photo_1 = models.ImageField(upload_to='clock_photos/', verbose_name='սլայդի նկար 1')
    slider_photo_2 = models.ImageField(upload_to='clock_photos/', verbose_name='սլայդի նկար 2')
    slider_photo_3 = models.ImageField(upload_to='clock_photos/', verbose_name='սլայդի նկար 3')
    slider_photo_4 = models.ImageField(upload_to='clock_photos/', verbose_name='սլայդի նկար 4')
    slider_photo_5 = models.ImageField(upload_to='clock_photos/', verbose_name='սլայդի նկար 5')
    youtube_link = models.TextField(verbose_name='Youtube Link', null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Ամսաթիվ')

    def __str__(self):
        return self.name


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Անվանում')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Ռուբրիկաներ'
        verbose_name = 'Ռուբրիկա'
        ordering = ['name']


class Information(models.Model):
    image1 = models.ImageField(upload_to='info/')
    description1 = models.TextField()
    image2 = models.ImageField(upload_to='info/')
    description2 = models.TextField()

    def __str__(self):
        return self.description1
    

class Color(models.Model):
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=7)

    def __str__(self):
        return self.name


class ClockColor(models.Model):
    clock = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)

main/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})

cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json

from main.models import Product
from .models import Cart, CartItemList
from .services import get_cart_items


def cart(request):
    total_cart_items = 0

    context = get_cart_items(request)
    if context['total_cart_items'] != 0:
        return render(request, 'main/cart.html', context)
    else:
        return render(request, 'main/empty_cart.html')


def update_cart(request):
    data = json.loads(request.body)

    product_id = data['productId']
    action = data['action']

    user = request.user
    product = Product.objects.get(id=product_id)
    cart_items, created = Cart.objects.get_or_create(user_id=user.id, completed=False)

    cart_item, created = CartItemList.objects.get_or_create(cart=cart_items, product=product)

    print(action)
    if action == 'add':
        cart_item.quantity = cart_item.quantity + 1
    elif action == 'remove':
        cart_item.quantity = cart_item.quantity - 1

    cart_item.save()

    if cart_item.quantity == 0:
        cart_item.delete()

    return JsonResponse('Item was added', safe=False)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

from cart.services import cart_item_counts
from .forms import LoginForm
from .models import *

from django.core.paginator import Paginator
import json
import random


def index(requset):
    clocks = list(Product.objects.filter(rubric__name='Clock'))
    random_clocks = random.sample(clocks, 2)
    decorations = list(Product.objects.filter(rubric__name='Decoration'))
    random_decorations = random.sample(decorations, 3)
    clocks_new = list(Product.objects.all())
    random_clocks_new = random.sample(clocks_new, 2)
    clocks_4_items = random.sample(clocks_new, 4)
    popular_items = Product.objects.filter(popular=1)
    total_cart_items = cart_item_counts(requset)['total_cart_items']

    context = {
        'navbar': 'index',
        'decorations': random_decorations,
        'clocks': random_clocks,
        'clocks_new': random_clocks_new,
        'clocks_4': clocks_4_items,
        'populars': popular_items,
        'total_cart_items': total_cart_items
    }
    return render(requset, 'main/index.html', context)


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('main:index')
        else:
            error = 'Invalid username or password.'
    else:
        form = LoginForm()
        error = None
    context = {
        'form': form,
        'error': 'Invalid username or password.',
    }
    return render(request, 'main/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('main:index')


# Search worked
def live_search(request):
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(name__icontains=query)
    else:
        products = Product.objects.none()

    return render(request, 'main/live_search.html', {
        'products': products,
        'query': query,
    })


def wallclocks_list(request):
    wallclocks = Product.objects.filter(rubric__name='Clock')
    paginator = Paginator(wallclocks, 5)
    page = request.GET.get('page')
    wallclocks = paginator.get_page(page)
    total_cart_items = cart_item_counts(request)['total_cart_items']
    context = {
        'wallclocks': wallclocks,
        'navbar': 'showClocks',
        'total_cart_items': total_cart_items
    }
    return render(request, 'main/wall_clocks.html', context)


def fireplace_list(request):
    fireplaces = Product.objects.filter(rubric__name='BioFireplace')
    paginator = Paginator(fireplaces, 5)
    page = request.GET.get('page')
    fireplaces = paginator.get_page(page)
    total_cart_items = cart_item_counts(request)['total_cart_items']

    context = {
        'fireplaces': fireplaces,
        'navbar': 'fireplace_list',
        'total_cart_items': total_cart_items,
    }
    return render(request, 'main/bio_fireplace.html', context)


def dolvano_home_list(request):
    dolvano_home = Product.objects.filter(rubric__name='DolvanoHome')
    paginator = Paginator(dolvano_home, 5)
    page = request.GET.get('page')
    dolvano_home = paginator.get_page(page)
    total_cart_items = cart_item_counts(request)['total_cart_items']
    context = {
        'dolvano_home': dolvano_home,
        'navbar': 'dolvano_home_list',
        'total_cart_items': total_cart_items
    }
    return render(request, 'main/dolvano_home.html', context)


def special_orders_list(request):
    special_orders = Product.objects.filter(rubric__name='SpecialOrders')
    paginator = Paginator(special_orders, 5)
    page = request.GET.get('page')
    special_orders = paginator.get_page(page)
    total_cart_items = cart_item_counts(request)['total_cart_items']

    context = {
        'special_orders': special_orders,
        'navbar': 'special_orders_list',
        'total_cart_items': total_cart_items,
    }
    return render(request, 'main/special_orders.html', context)


def information(requset):
    information = Information.objects.all()
    total_cart_items = cart_item_counts(requset)['total_cart_items']

    context = {
        'navbar': 'information',
        'information': information,
        'total_cart_items': total_cart_items,
    }
    return render(requset, 'main/information.html', context)


# Don't finish
def decoration_list(request):
    decorations = Product.objects.filter(rubric__name='Decoration')
    paginator = Paginator(decorations, 5)
    page = request.GET.get('page')
    decorations = paginator.get_page(page)
    total_cart_items = cart_item_counts(request)['total_cart_items']

    context = {
        'decorations': decorations,
        'navbar': 'decorations_link',
        'total_cart_items': total_cart_items,

    }
    return render(request, 'main/decorations.html', context)


def product_page(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    return render(request, 'main/one_product_page.html',
                  {
                      'product': product
                  }
                  )


def test1(request, id):
    clock = Clock.objects.get(pk=id)
    clock_colors = clock.clockcolor_set.values_list('color__name', flat=True)

    return render(request, 'main/test1.html', {
        'colors': clock_colors
    })

main/templates/main/bio_fireplace.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Bio Fireplace {% endblock %}


{%block content%}

    <main>
        <section class="sec category_banner">
            <div class="position-relative overflow-hidden">
                <img src="{% static 'main/images/dolvano_banner_2.jpg' %}" alt="img" width="100%" height="50%">
                <div class="item_attributs">
                    <!-- <p>BP-007</p>
                <a href="#" class="btn btn-outline-primary banner-btn">Заказать</a> -->
                </div>
            </div>
        </section>

        <section class="sec py-5">
            <div class="container">
                <div class="row justify-content-around">
                    <h1 class="text-white text-uppercase text-center">Bio Fireplace</h1>
                </div>
            </div>
            <div class="container-sm">
                <div class="row sec_1_2">
                    {%for fireplace in fireplaces %}
                <div class="product__card__col col d-flex flex-column mb-3">
                    <div class="product__card position-relative z-0">
                        <a href="{% url 'main:product_page' product_pk=fireplace.pk %}" class="product_hide position-absolute w-100 h-100 z-3"></a>
                        <div class="product__card__image position-absolute start-50 top-50 translate-middle z-2">
                            <img src="{{fireplace.card_photo.url}}" alt="image" width="100%" class="z-2">
                        </div>
                        <div class="product__add__button position-absolute z-3 end-0 m-4">
                            <div  data-id="{{ fireplace.pk }}" data-action="add"  class="add-btn update-cart product__add__button__circle d-flex justify-content-center align-items-center">
                                <span ><i class="fa-solid fa-plus text-white"></i></span>
                            </div>
                        </div>
                    </div>
                    <footer class="mt-3">
                        <h1 class="text-white fs-5">{{fireplace.name}}</h1>
                        <p class="text-white fs-6">{{fireplace.price}}$</p>
                    </footer>
                </div>
                {%endfor%}
                </div>
                <div class="pagination d-flex justify-content-center">
                    <span class="step-links">
                      {% if fireplaces.has_previous %}
                        <a href="?page=1" class="text-white">&laquo; first</a>
                        <a href="?page={{ fireplaces.previous_page_number }}">previous</a>
                      {% endif %}
                  
                      <span class="current-page text-white">
                        {{ fireplaces.number }} of {{ fireplaces.paginator.num_pages }}
                      </span>
                  
                      {% if fireplaces.has_next %}
                        <a href="?page={{ fireplaces.next_page_number }}" class="text-white">next</a>
                        <a href="?page={{ fireplaces.paginator.num_pages }}" class="text-white">last &raquo;</a>
                      {% endif %}
                    </span>
                  </div>
            </div>
        </section>
    </main>
{% endblock %}

main/templates/main/cart.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

          <section class="sec category_banner">
            <div class="position-relative overflow-hidden">
                <img src="{% static 'main/images/dolvano_banner_2.jpg' %}" alt="img" width="100%" height="50%">
                <div class="item_attributs">
                    <!-- <p>BP-007</p>
                <a href="#" class="btn btn-outline-primary banner-btn">Заказать</a> -->
                </div>
            </div>
        </section>

     <section class="sec py-5">
	<div class="row-center container-sm sec py-5">
		<div class="col-lg-12">
			<div class="box-element">

{#				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Continue Shopping</a>#}

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{cart_items.get_cart_total_quantity}}</strong></h5></th>
						<th><h5>Total:<strong> ${{cart_items.get_total_cart_price|floatformat:2}}</strong></h5></th>
						<th>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.card_photo.url}}" alt="product image"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-id="{{item.product.id}}" data-action="add"
                                 class="chg-quantity update-cart" src="{% static  'main/images/add.png' %}" alt="increase">

							<img data-id="{{item.product.id}}" data-action="remove"
                                 class="chg-quantity update-cart" src="{% static  'main/images/minus.png' %}" alt="decrease">
						</div>
					</div>
					<div style="flex:1"><p>${{item.get_product_total_price|floatformat:2}}</p></div>

				</div>
				{% endfor %}
			</div>
		</div>
	</div>
     </section>


{% endblock content %}

main/templates/main/decorations.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Mirror Decor {% endblock %}


{%block content%}

    <main>
        <section class="sec category_banner">
            <div class="position-relative overflow-hidden">
                <img src="{% static 'main/images/dolvano_banner_2.jpg' %}" alt="img" width="100%" height="50%">
                <div class="item_attributs">
                    <!-- <p>BP-007</p>
                <a href="#" class="btn btn-outline-primary banner-btn">Заказать</a> -->
                </div>
            </div>
        </section>

        <section class="sec py-5">
            <div class="container">
                <div class="row justify-content-around">
                    <h1 class="text-white text-uppercase text-center">decorations</h1>
                </div>
            </div>
            <div class="container-sm">
                <div class="row sec_1_2">
                    {%for decoration in decorations %}
                <div class="product__card__col col d-flex flex-column mb-3">
                    <div class="product__card position-relative z-0">
                        <a href="{% url 'main:product_page' product_pk=decoration.pk %}" class="product_hide position-absolute w-100 h-100 z-3"></a>
                        <div class="product__card__image position-absolute start-50 top-50 translate-middle z-2">
                            <img src="{{decoration.card_photo.url}}" alt="image" width="100%" class="z-2">
                        </div>
                        <div class="product__add__button position-absolute z-3 end-0 m-4">
                            <div  data-id="{{ decoration.pk }}" data-action="add"  class="add-btn update-cart product__add__button__circle d-flex justify-content-center align-items-center">
                                <span ><i class="fa-solid fa-plus text-white"></i></span>
                            </div>
                        </div>
                    </div>
                    <footer class="mt-3">
                        <h1 class="text-white fs-5">{{decoration.name}}</h1>
                        <p class="text-white fs-6">{{decoration.price}}$</p>
                    </footer>
                </div>
                {%endfor%}
                </div>
                <div class="pagination d-flex justify-content-center">
                    <span class="step-links">
                      {% if decorations.has_previous %}
                        <a href="?page=1" class="text-white">&laquo; first</a>
                        <a href="?page={{ decorations.previous_page_number }}">previous</a>
                      {% endif %}
                  
                      <span class="current-page text-white">
                        {{ decorations.number }} of {{ decorations.paginator.num_pages }}
                      </span>
                  
                      {% if decorations.has_next %}
                        <a href="?page={{ decorations.next_page_number }}" class="text-white">next</a>
                        <a href="?page={{ decorations.paginator.num_pages }}" class="text-white">last &raquo;</a>
                      {% endif %}
                    </span>
                  </div>
            </div>
        </section>
    </main>
{% endblock %}

main/templates/main/dolvano_home.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Dolvano Home {% endblock %}


{%block content%}

    <main>
        <section class="sec category_banner">
            <div class="position-relative overflow-hidden">
                <img src="{% static 'main/images/dolvano_banner_2.jpg' %}" alt="img" width="100%" height="50%">
                <div class="item_attributs">
                    <!-- <p>BP-007</p>
                <a href="#" class="btn btn-outline-primary banner-btn">Заказать</a> -->
                </div>
            </div>
        </section>

        <section class="sec py-5">
            <div class="container">
                <div class="row justify-content-around">
                    <h1 class="text-white text-uppercase text-center">Dolvano Home</h1>
                </div>
            </div>
            <div class="container-sm">
                <div class="row sec_1_2">
                    {%for item in dolvano_home %}
                <div class="product__card__col col d-flex flex-column mb-3">
                    <div class="product__card position-relative z-0">
                        <a href="{% url 'main:product_page' product_pk=item.pk %}" class="product_hide position-absolute w-100 h-100 z-3"></a>
                        <div class="product__card__image position-absolute start-50 top-50 translate-middle z-2">
                            <img src="{{item.card_photo.url}}" alt="image" width="100%" class="z-2">
                        </div>
                        <div class="product__add__button position-absolute z-3 end-0 m-4">
                            <div  data-id="{{ item.pk }}" data-action="add"  class="add-btn update-cart product__add__button__circle d-flex justify-content-center align-items-center">
                                <span ><i class="fa-solid fa-plus text-white"></i></span>
                            </div>
                        </div>
                    </div>
                    <footer class="mt-3">
                        <h1 class="text-white fs-5">{{item.name}}</h1>
                        <p class="text-white fs-6">{{item.price}}$</p>
                    </footer>
                </div>
                {%endfor%}
                </div>
                <div class="pagination d-flex justify-content-center">
                    <span class="step-links">
                      {% if dolvano_home.has_previous %}
                        <a href="?page=1" class="text-white">&laquo; first</a>
                        <a href="?page={{ dolvano_home.previous_page_number }}">previous</a>
                      {% endif %}
                  
                      <span class="current-page text-white">
                        {{ dolvano_home.number }} of {{ dolvano_home.paginator.num_pages }}
                      </span>
                  
                      {% if dolvano_home.has_next %}
                        <a href="?page={{ dolvano_home.next_page_number }}" class="text-white">next</a>
                        <a href="?page={{ dolvano_home.paginator.num_pages }}" class="text-white">last &raquo;</a>
                      {% endif %}
                    </span>
                  </div>
            </div>
        </section>
    </main>
{% endblock %}

main/templates/main/empty_cart.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

          <section class="sec category_banner">
            <div class="position-relative overflow-hidden">
                <img src="{% static 'main/images/dolvano_banner_2.jpg' %}" alt="img" width="100%" height="50%">
                <div class="item_attributs">
                    <!-- <p>BP-007</p>
                <a href="#" class="btn btn-outline-primary banner-btn">Заказать</a> -->
                </div>
            </div>
        </section>

     <section class="sec py-5">
	<div class="row-center">
        
        <div class="container-fluid  mt-100">
				 <div class="row">
				 
					<div class="col-md-12">
					
							<div class="card">
						<div class="card-header">
						</div>
						<div class="card-body cart">
								<div class="col-sm-12 empty-cart-cls text-center">
									<img src="{% static 'main/images/empty_cart.png' %}" width="130" height="130" class="img-fluid mb-4 mr-3" alt="empty">
									<h3><strong>Your Cart is Empty</strong></h3>
									<h4>Go to shop pages and add something</h4>
									<a href="{% url 'main:wallclocks_list' %}" class="btn btn-primary cart-btn-transform m-3" data-abc="true">Start shopping</a>

								
								</div>
						</div>
				</div>

					
					</div>
				 
				 </div>
				
				</div>

	</div>
     </section>


{% endblock content %}

main/templates/main/live_search.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{query}} {% endblock %}


{%block content%}

    <main>
        <section class="sec category_banner">
            <div class="position-relative overflow-hidden">
                <img src="{% static 'main/images/dolvano_banner_2.jpg' %}" alt="img" width="100%" height="50%">
                <div class="item_attributs">
                </div>
            </div>
        </section>

        <section class="sec dolvano_info py-5">
            <h1 class="fs-xx-large text-center mb-3" style="color: white;" id="search_result">Search result</h1>
            <div class="container">
            <section class="sec dolvano_info py-5">
            <div class="container-sm">
                <div class="row sec_1_2">
                  {% for product in products %}
                  <div class="product__card__col col d-flex flex-column mb-3">
                    <div class="product__card position-relative">
                        <a href="{% url 'main:product_page' product_pk=product.pk %}" class="product_hide position-absolute w-100 h-100 z-3"></a>
                        <div class="product__card__image position-absolute start-50 top-50 translate-middle z-2">
                            <img src="{{product.card_photo.url}}" alt="image" width="100%" class="z-2">
                        </div>
                        <div class="product__add__button position-absolute z-3 end-0 m-4">
                            <div class="product__add__button__circle update-cart d-flex justify-content-center align-items-center">
                                <a href="#"><i class="fa-solid fa-plus text-white"></i></a>
                            </div>
                        </div>
                    </div>
                    <footer class="mt-3">
                        <h1 class="text-white fs-5">{{product.name}}</h1>
                        <p class="text-white fs-6">{{product.price}}$</p>
                    </footer>
                </div>
                  {% endfor %}
            </div>
        </section>

    </main>
{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Login {% endblock %}


{% block active_link %}
nav-link-active
{% endblock %}


{%block content%}
<style>
        label,h1{
            color: white;
        }
    </style>
<main>
    <section class="sec category_banner">
        <div class="position-relative overflow-hidden">
            <img src="{% static 'main/images/dolvano_banner_2.jpg' %}" alt="img"
                width="100%" height="50%">
        </div>
    </section>
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{error}}
      </div>
    {% endif %}
    <div id="login_form" class="mb-5 opacity-0">Lorem ipsum dolor sit amet.</div>

    <div class="container m-5 w-50 d-flex justify-content-center
        align-items-center mx-auto">

        <form method="post" class="my-4">
            {% csrf_token %}
            <h1 class="text-center">Login</h1>
            <div class="form-group my-3">
                <label for="{{ form.username.id_for_label }}">Username:</label> 
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="{{ form.password.id_for_label }}">Password:</label>
                {{ form.password }}
            </div>
            <div class="d-flex justify-content-center mt-3">
                <input type="submit" value="Login" class="btn btn-primary">
            </div>
            <div class="d-flex justify-content-center mt-3">
               <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Register</a>
            </div>
        </form>
    </div>


</main>
{%endblock%}